output:
  # Make output more digestible with quickfix in vim/emacs/etc.
  sort-results: true
  print-issued-lines: false

linters:
  # We'll track the golangci-lint default linters manually
  # instead of letting them change without our control.
  disable-all: true
  enable:
    # golangci-lint defaults:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Our own extras:
    - gofmt
    - nolintlint # lints nolint directives
    - revive

linters-settings:
  govet:
    # These govet checks are disabled by default, but they're useful.
    enable:
      - niliness
      - reflectvaluecompare
      - sortslice
      - unusedwrite

issues:
  # Print all issues reported by all linters.
  max-issues-per-linter: 0
  max-same-issues: 0

  # Don't ignore some of the issues that golangci-lint considers okay.
  # This includes documenting all exported entities.
  exclude-use-default: false

  exclude-rules:
    # Don't warn on unused parameters.
    # Parameter names are useful; replacing them with '_' is undesirable.
    - linters: [revive]
      text: 'unused-parameter: parameter \S+ seems to be unused, consider removing or renaming it as _'

    # staticcheck already has smarter checks for empty blocks.
    # revive's empty-block linter has false positives.
    # For example, as of writing this, the following is not allowed.
    #   for foo() { }
    - linters: [revive]
      text: 'empty-block: this block is empty, you can remove it'

    # We're using a pretty pedantic style for revive.
    # Generated files cannot always comply with it, so omit them.
    - linters: [revive]
      path: '_gen.go$'

    # Also opt-out revive for source files used in examples.
    # The contents of those source files affect the documentation,
    # so we want to control their contents.
    - linters: [revive]
      path: 'docs/ex/.*.go$'

    # magic_gen has some generated code that writes to fields of a struct
    # that eventually goes unused.
    # This is a false positive -- that struct is intentionally unused.
    - linters: [govet]
      path: examples/magic_gen.go
      text: 'unusedwrite: unused write to field'
