name: GitHub Pages

on:
  push:
    branches: [main]

  # This lets us publish the workflow
  # manually from the GitHub Actions UI.
  workflow_dispatch:

# Run at most one publish job at a time,
# cancelling others if a new one starts.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          cache-dependency-path: docs/yarn.lock

      - name: Install dependencies
        run: yarn install
        working-directory: docs

      - name: Build
        run: make docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/dist/

  deploy:
    needs: build  # run only after a successful build

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.output.pages_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
